language: node_js
node_js: 10.13.0
cache:
  yarn: true
branches:
  only:
    - master
before_install:
- nvm install 10.13.0
- nvm alias default v10.13.0
- nvm use v10.13.0
install:
- yarn install
script:
- yarn test
